export const REPORT_FIELDS = {
  "BLOOD UREA NITROGEN (BUN)": "bun",
  "BLOOD UREA NITROGEN": "bun",
  "BUN": "bun",
  "THYROID STIMULATING HORMONE (TSH)": "tsh",
  "THYROID STIMULATING HORMONE": "tsh",
  "TSH": "tsh",
  "ALKALINE PHOSPHATASE (SAP)": "alkaline_phosphatase",
  "ALKALINE PHOSPHATASE": "alkaline_phosphatase",
  "VITAMIN D (25-HYDROXY VIT D)": "vitamin_d",
  "VITAMIN D (25-HYDROXY)": "vitamin_d",
  "VITAMIN D3": "vitamin_d",
  "VITAMIN D": "vitamin_d",
  "MCHC (MEAN CORPUSCULAR HEMOGLOBIN CONCENTRATION)": "mchc",
  "MCV (MEAN CORPUSCULAR VOLUME)": "mcv",
  "MCH (MEAN CORPUSCULAR HEMOGLOBIN)": "mch",
  "HAEMOGLOBIN": "hemoglobin",
  "HEMOGLOBIN": "hemoglobin",
  "RBC COUNT": "rbc",
  "WBC COUNT": "wbc",
  "PLATELET COUNT": "platelets",
  "PACKED CELL VOLUME": "hematocrit",
  "VITAMIN B12": "vitamin_b12",
  "PHOSPHORUS": "phosphorus",
  "PCT": "pct",
  "CALCIUM": "calcium",
  "SERUM FERRITIN": "ferritin",
  "FERRITIN": "ferritin",
  "TOTAL CHOLESTEROL": "cholesterol",
  "TRIGLYCERIDES": "triglycerides",
  "HDL CHOLESTEROL": "hdl",
  "LDL CHOLESTEROL": "ldl",
  "TOTAL BILIRUBIN": "bilirubin",
  "ALT (SGPT)": "alt",
  "AST (SGOT)": "ast",
  "ALBUMIN": "albumin",
  "SERUM CREATININE": "creatinine",
  "CREATININE": "creatinine",
  "SERUM UREA": "urea",
  "BLOOD UREA": "urea",
  "UREA": "urea",
  "URIC ACID": "uric_acid",
  "FASTING GLUCOSE": "glucose_fasting",
  "GLUCOSE FASTING": "glucose_fasting",
  "GLUCOSE": "glucose_fasting",
  "HBA1C": "hba1c",
  "SODIUM": "sodium",
  "POTASSIUM": "potassium"
};

export function normalize(text) {
  return String(text || "").toLowerCase().trim().replace(/\./g, "").replace(/[-_]/g, " ");
}
